### ISSUE TITLE
Missing MixedFraction.fromDouble

### ISSUE THREAD

**Issue by radicand** [albertodev01/fraction#18]
**Describe the bug**
The docs describe a method called `MixedFraction.fromDouble` that does not seem to be implemented.

**To Reproduce**
1. Write code that calls `MixedFraction.fromDouble(1.5)`
2. See error

**Expected behavior**
A MixedFraction

**Additional context**
The only reference I can find is in the docs, it's unclear if it's a documentation issue or a missing implementation.

**Comment by albertodev01** [comment]
Thank you for reporting the issue 😁

I am on holiday and I will come back this weekend, expect the fix to be on pub by sunday!

**Comment by albertodev01** [comment]
Sorry it took a few but changes are on `develop` 😄 I'm making some smaller fixes and then I'll publish tomorrow

**Comment by radicand** [comment]
Thanks!

**Comment by albertodev01** [comment]
@radicand Published v 4.1.2 😄
