### ISSUE TITLE
Sometimes, I'm getting a '0/10' tagged to the end of the result.

### ISSUE THREAD

**Issue by litopjos** [albertodev01/fraction#6]
I'm using the package as an input preprocessor to my app. In my case, I have an input that I let my users enter either a whole number, a number with a decimal, or a fraction / mixed fraction. I then use the package to deal with the fraction / mixed fraction input types to convert it to a double.

When I enter the whole number 8 to the code below, the result is a string '8 0/1'.
Is there any way to get rid of '0/1' bit? I know I can parse it out, but it would be neater for the package not to return it.

Thanks.

String result = MixedFraction.fromFraction(Fraction.fromDouble(amount)).toString();

**Comment by albertodev01** [comment]
Hello!

I'll fix this in version 2.0 (which comes with null safety). I'll close the issue for now because this is already going to be implemented in the new version 😃
