### ISSUE TITLE
analysis_options.dart contains 'dart_code_metrics' configuration but doesn't actually use the package

### ISSUE THREAD

**Issue by wujek-srujek** [albertodev01/fraction#7]
Here https://github.com/albertodev01/fraction/blob/master/analysis_options.yaml#L8 you can find configuration for the package, but the `pubspec.yaml` actually never uses the package (https://pub.dev/packages/dart_code_metrics#usage). This is confusing and you could either remove the config or use the package, especially since this is the example from your book, with newcomers in mind.

**Comment by albertodev01** [comment]
Thank you very much! I have forgotten to include that in the `dev_dependencies`, I will fix it by this evening!

**Comment by albertodev01** [comment]
I have decided to remove (for now) the `dart_code_metrics` section because they haven't migrated to null safety yet. I'll bring this back as soon as they relase a null safe version!
